import Link from 'next/link';
import {whatsappUrl} from '@/lib/contact';
import { notFound } from 'next/navigation';
import { clubs } from '@/lib/content';
import {pageMetadata,siteUrl} from '@/lib/seo';
import StructuredData from '@/components/structured-data';
export function generateStaticParams(){return clubs.map(c=>({slug:c.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const c=clubs.find(c=>c.slug===slug);return c?pageMetadata(`${c.name} · Johor, Malaysia`,`${c.name}, club ${c.number}, belongs to Division G Area ${c.area} in Johor, Malaysia. Find visitor information and confirm meeting arrangements.`,`/clubs/${c.slug}`):{title:'Club not found'};}
export default async function ClubPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const c=clubs.find(c=>c.slug===slug); if(!c)notFound(); return <article className="section article"><StructuredData data={{'@context':'https://schema.org','@type':'Organization',name:c.name,identifier:c.number,url:`${siteUrl}/clubs/${c.slug}`,areaServed:{'@type':'AdministrativeArea',name:'Johor, Malaysia'},parentOrganization:{'@id':`${siteUrl}/#organization`}}}/><Link href="/clubs" className="text-link">← All clubs</Link><p className="eyebrow">JOHOR, MALAYSIA · AREA {c.area} · DIVISION G</p><h1>{c.name}</h1><p className="intro">{c.description??`A Toastmasters club in Johor, Malaysia, belonging to District 102 Division G, Area ${c.area}. Meeting and visitor information will be added when available.`}</p><Link className="text-link" href="/visit">Plan your first club visit →</Link><p><a className="button" href={whatsappUrl(c)} target="_blank" rel="noreferrer">Ask Division G about this club ↗</a></p><dl><dt>Club number</dt><dd>{c.number}</dd><dt>Location</dt><dd>{c.city??'To be confirmed'}</dd><dt>Meeting</dt><dd>{c.meeting?`${c.meeting} · Malaysia time`:'To be confirmed'}</dd><dt>Venue</dt><dd>{c.venue??'To be confirmed'}</dd><dt>Format / language</dt><dd>{c.format??'To be confirmed'} / {c.language??'To be confirmed'}</dd></dl><a className="button" href={c.website??'https://www.toastmasters.org/find-a-club'} target="_blank" rel="noreferrer">{c.website?'Contact the club ↗':'Official club finder ↗'}</a><p className="fine">Club name, number, and area from the roster supplied on 8 October 2026. Search the official club finder using club number {c.number}. Confirm arrangements before visiting.</p></article>;}
