'use client';
import { useState } from 'react';
import Link from 'next/link';
import {copy,languagePath,localTerm,localMeeting,type Locale} from '@/lib/languages';
import type { Club } from '@/lib/content';
export default function Directory({ clubs,locale="en" }: { clubs: Club[];locale?:Locale }) {
  const t=copy[locale];
  const [query,setQuery]=useState(''); const [format,setFormat]=useState(''); const [area,setArea]=useState(''); const [language,setLanguage]=useState('');
  const filtered=clubs.filter(c=>`${c.name} ${c.number} ${c.city??''} ${c.venue??''}`.toLowerCase().includes(query.trim().toLowerCase())&&(!format||(format==='pending'?!c.format:c.format===format))&&(!area||c.area===area)&&(!language||(language==='pending'?!c.language:c.language===language)));
  return <><div className="filters"><label>{t.search}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.placeholder}/></label><label>{t.area}<select value={area} onChange={e=>setArea(e.target.value)}><option value="">{t.allAreas}</option>{Array.from(new Set(clubs.map(c=>c.area))).sort().map(a=><option key={a}>{a}</option>)}</select></label><label>{t.format}<select value={format} onChange={e=>setFormat(e.target.value)}><option value="">{t.allFormats}</option><option value="pending">{t.pending}</option>{Array.from(new Set(clubs.flatMap(c=>c.format?[c.format]:[]))).sort().map(f=><option key={f} value={f}>{localTerm(f,locale)}</option>)}</select></label><label>{t.meetingLanguage}<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">{t.allLanguages}</option>{Array.from(new Set(clubs.flatMap(c=>c.language?[c.language]:[]))).sort().map(l=><option key={l} value={l}>{localTerm(l,locale)}</option>)}</select></label></div><p className="result-count" role="status">{filtered.length} {t.found}</p>{filtered.length?<div className="three-grid">{filtered.map(c=><Link className="club-card" href={languagePath(locale,`/clubs/${c.slug}`)} key={c.slug}><p className="eyebrow">{t.area} {c.area}{c.format?` · ${localTerm(c.format,locale)}`:''}</p><h2>{c.name}</h2><p>{t.number} #{c.number}</p>{(c.city||c.language)&&<p>{[c.city,localTerm(c.language,locale)].filter(Boolean).join(' · ')}</p>}<p>{localMeeting(c.meeting,locale)}</p>{c.membership&&<p><strong>{localTerm(c.membership,locale)}</strong></p>}{c.meetingNote&&<p className="fine">{t.confirm}</p>}<span className="text-link">{t.details} ↗</span></Link>)}</div>:<div className="empty"><span>✦</span><h2>{clubs.length?t.noResults:'Your community directory is taking shape.'}</h2><p>{clubs.length?t.tryAgain:'We are preparing verified Division G listings. In the meantime, use the official Toastmasters club finder and confirm division membership with District 102.'}</p>{clubs.length?<button className="button" onClick={()=>{setQuery('');setArea('');setFormat('');setLanguage('');}}>{t.reset}</button>:<a className="button" href="https://www.toastmasters.org/find-a-club" target="_blank" rel="noreferrer">Official club finder ↗</a>}</div>}</>;
}
