'use client';
import { useState } from 'react';
import Link from 'next/link';
import type { Club } from '@/lib/content';
export default function Directory({ clubs }: { clubs: Club[] }) {
  const [query,setQuery]=useState(''); const [format,setFormat]=useState(''); const [area,setArea]=useState(''); const [language,setLanguage]=useState('');
  const filtered=clubs.filter(c=>`${c.name} ${c.city} ${c.venue}`.toLowerCase().includes(query.toLowerCase())&&(!format||c.format===format)&&(!area||c.area===area)&&(!language||c.language===language));
  return <><div className="filters"><label>Search clubs<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Club name or location"/></label><label>Area<select value={area} onChange={e=>setArea(e.target.value)}><option value="">All areas</option>{Array.from(new Set(clubs.map(c=>c.area))).sort().map(a=><option key={a}>{a}</option>)}</select></label><label>Meeting format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="">All formats</option>{['In person','Online','Hybrid'].map(f=><option key={f}>{f}</option>)}</select></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">All languages</option>{Array.from(new Set(clubs.map(c=>c.language))).sort().map(l=><option key={l}>{l}</option>)}</select></label></div><p className="result-count" role="status">{filtered.length} {filtered.length===1?'club':'clubs'} found</p>{filtered.length?<div className="three-grid">{filtered.map(c=><Link className="club-card" href={`/clubs/${c.slug}`} key={c.slug}><p className="eyebrow">AREA {c.area} · {c.format}</p><h2>{c.name}</h2><p>{c.city} · {c.language}</p><p>{c.meeting}</p><span className="text-link">Meet the club ↗</span></Link>)}</div>:<div className="empty"><span>✦</span><h2>{clubs.length?'No clubs match those filters.':'Your community directory is taking shape.'}</h2><p>{clubs.length?'Try another location or reset the filters.':'We are preparing verified Division G listings. In the meantime, use the official Toastmasters club finder and confirm division membership with District 102.'}</p>{clubs.length?<button className="button" onClick={()=>{setQuery('');setArea('');setFormat('');setLanguage('');}}>Reset filters</button>:<a className="button" href="https://www.toastmasters.org/find-a-club" target="_blank" rel="noreferrer">Official club finder ↗</a>}</div>}</>;
}
