import VenueLink from '@/components/venue-link';
import Link from 'next/link';
import Image from 'next/image';
import {clubs,posts} from '@/lib/content';
import {copy,htmlLanguage,languagePath,localMeeting,localTerm,type Locale} from '@/lib/languages';
import Directory from '@/components/directory';
import ClubMap from '@/components/club-map';
import SocialFeedCard from '@/components/social-feed';
import {whatsappUrl,contactDisplay} from '@/lib/contact';
import StructuredData from '@/components/structured-data';
import {siteUrl} from '@/lib/seo';

export default function TranslatedPage({locale,path}:{locale:Locale;path:string[]}){
 const t=copy[locale],url=(p:string)=>languagePath(locale,p),route=path[0]??'',club=clubs.find(c=>c.slug===path[1]),post=posts.find(p=>p.slug===path[1]);
 const notes:Record<string,string>=locale==='zh'?{'07430237':'来源中同时列出每月第1个星期四及第1和第3个星期四。请联系 Division G 确认最新会议安排。','01475566':'来源列出线上会议，同时提供 Info Agency 地址。出发前请确认线上链接，以及是否有实体会议。','00002196':'会议表列出 Zoom 线上会议，地点表则列出 Johor Jaya Daiman Bowl。请联系 Division G 确认最新安排。'}:{'07430237':'Sumber menyenaraikan Khamis minggu pertama serta Khamis minggu pertama dan ketiga. Sahkan jadual terkini dengan Division G.','01475566':'Sumber menyenaraikan mesyuarat dalam talian dan alamat Info Agency. Sahkan pautan dalam talian serta ketersediaan mesyuarat bersemuka sebelum perjalanan.','00002196':'Jadual menyenaraikan mesyuarat Zoom, manakala sumber lokasi menyenaraikan Johor Jaya Daiman Bowl. Sahkan aturan terkini dengan Division G.'};
 const cta=<div className="actions"><Link className="button" href={url('/clubs')}>{t.clubs} ↗</Link><a className="text-link" href={whatsappUrl()} target="_blank" rel="noreferrer">{t.enquire} ↗</a></div>;
 const benefits=<div className="three-grid">{[[t.speaking,t.speakingText],[t.feedback,t.feedbackText],[t.leadership,t.leadershipText]].map(([title,text])=><div className="post-copy" key={title}><h2>{title}</h2><p>{text}</p></div>)}</div>;
 const articles=<div className="three-grid">{[...posts].sort((a,b)=>Number(b.lang===htmlLanguage[locale].split('-MY')[0])-Number(a.lang===htmlLanguage[locale].split('-MY')[0])).map(p=><Link lang={p.lang} className="post-card" href={url(`/blog/${p.slug}`)} key={p.slug}><div className="post-copy"><p className="eyebrow">{p.lang==='zh-Hans'?'中文':p.lang==='ms'?'Bahasa Melayu':'English'} · {p.readTime}</p><h2>{p.title}</h2><p>{p.summary}</p><span className="text-link">{t.read} ↗</span></div></Link>)}</div>;
 if(route==='clubs'&&club)return <article className="section article"><StructuredData data={{'@context':'https://schema.org','@type':'Organization',name:club.name,identifier:club.number,url:siteUrl+url(`/clubs/${club.slug}`),sameAs:club.facebook?[club.facebook]:undefined,areaServed:'Johor, Malaysia'}}/><Link className="text-link" href={url('/clubs')}>← {t.back}</Link><p className="eyebrow">DIVISION G · {t.area} {club.area}</p><h1>{club.name}</h1><p className="intro">{t.confirm}</p><p><a className="button" href={whatsappUrl(club)} target="_blank" rel="noreferrer">{t.enquire} ↗</a></p><dl>{[[t.number,club.number],[t.location,club.city??t.pending],[t.meeting,localMeeting(club.meeting,locale)],[t.venue,club.venue??t.pending],[t.format,localTerm(club.format,locale)],[t.meetingLanguage,localTerm(club.language,locale)],[t.membership,localTerm(club.membership,locale)]].map(([label,value])=><div className="detail-pair" key={label}><dt>{label}</dt><dd>{label===t.venue&&club.venue?<VenueLink venue={club.venue}/>:value}</dd></div>)}</dl>{club.meetingNote&&<aside className="article-aside"><h2>{t.step2}</h2><p>{t.confirm}</p><p>{notes[club.number]??t.confirm}</p></aside>}<a className="text-link" href="https://www.toastmasters.org/find-a-club" target="_blank" rel="noreferrer">{t.finder} ↗</a><section className="club-social"><h2>{t.updates}</h2>{club.facebook?(club.facebook.includes('/groups/')?<p><a className="text-link" href={club.facebook} target="_blank" rel="noreferrer">{t.group} ↗</a> {t.groupNote}</p>:<SocialFeedCard locale={locale} feed={{id:club.number,title:club.name,platform:'facebook',url:club.facebook}}/>):<p>{t.missing}</p>}</section><p className="fine">{t.source}</p></article>;
 if(route==='blog'&&post)return <article className="section article"><Link className="text-link" href={url('/blog')}>← {t.blog}</Link>{post.lang==='en'&&<p>{t.articleEnglish}</p>}<div lang={post.lang}><p className="eyebrow">{post.category} · {post.readTime}</p><h1>{post.title}</h1><p className="intro">{post.summary}</p><div className="prose">{post.paragraphs.map(text=><p key={text}>{text}</p>)}</div></div><aside className="article-aside"><h2>{t.visit}</h2><p>{t.visitText}</p>{cta}</aside></article>;
 const titles:Record<string,string>={'':t.home,clubs:t.clubs,blog:t.blog,'why-us':t.whyTitle,'connect-with-us':t.connect,about:t.community,visit:t.visit};
 return <section className={`section ${['about','visit','connect-with-us'].includes(route)?'article':'page-section'}`}><p className="eyebrow">DISTRICT 102 · DIVISION G · JOHOR, MALAYSIA</p><h1>{titles[route]}</h1><p className="intro">{route==='about'?t.aboutText:route==='connect-with-us'?t.connectText:route==='visit'?t.visitText:t.intro}</p>{route===''&&<>{cta}{benefits}<p>{t.languages}</p><Link className="text-link" href={url('/why-us')}>{t.why} →</Link><ClubMap locale={locale}/></>}{route==='clubs'&&<><p>{t.languages} {t.confirm}</p><ClubMap locale={locale}/><Directory clubs={clubs} locale={locale}/></>}{route==='blog'&&articles}{route==='why-us'&&<>{benefits}{cta}<p>{t.languages} {t.confirm}</p>{articles}</>}{route==='connect-with-us'&&<><section className="club-social"><SocialFeedCard locale={locale} feed={{id:'division-g-facebook',title:'Toastmasters District 102 Division G',platform:'facebook',url:'https://www.facebook.com/tmd102divg'}}/></section><h2>{t.visit}</h2><p>{t.visitText}</p>{cta}</>}{route==='about'&&<><h2>{t.council}</h2><figure className="council-poster"><a href="/images/division-g-council-2026-2027.png" target="_blank" rel="noreferrer"><Image src="/images/division-g-council-2026-2027.png" alt={t.council} width={1024} height={1536} sizes="(max-width: 860px) 90vw, 774px"/></a><figcaption><a className="text-link" href="/images/division-g-council-2026-2027.png" target="_blank" rel="noreferrer">{t.fullPoster} ↗</a></figcaption></figure><div className="prose"><h2>{t.district}</h2><p>{t.districtText}</p><a className="text-link" href="https://d102tm.org/" target="_blank" rel="noreferrer">{t.district} ↗</a><h2>{t.visit}</h2><p>{t.languages}</p><p>{t.confirm}</p></div>{cta}</>}{route==='visit'&&<><aside className="article-aside"><h2>{t.enquire}</h2><p>{t.visitText}</p><a className="button" href={whatsappUrl()} target="_blank" rel="noreferrer">WhatsApp {contactDisplay} ↗</a></aside><div className="prose"><h2>{t.step1}</h2><p>{t.intro}</p><Link className="text-link" href={url('/clubs')}>{t.clubs} →</Link><h2>{t.step2}</h2><p>{t.languages}</p><p>{t.confirm}</p><h2>{t.step3}</h2><p>{t.step3Text}</p><a className="text-link" href="https://www.toastmasters.org/find-a-club" target="_blank" rel="noreferrer">{t.finder} ↗</a></div></>}</section>;
}
