import {languagePath} from './languages';
import type { Metadata } from 'next';
export const siteUrl='https://d102-division-g.vercel.app';
export function pageMetadata(title:string,description:string,path:string):Metadata{return {title,description,alternates:{canonical:path,languages:{'en-MY':path,'zh-Hans':languagePath('zh',path),'ms-MY':languagePath('ms',path)}},openGraph:{title,description,url:path,siteName:'Toastmasters Johor · Division G',locale:'en_MY',type:'website'},twitter:{card:'summary',title,description}};}
export const faqs=[
 {question:'Which languages do Toastmasters clubs in Division G use?',answer:'Fifteen Division G clubs conduct meetings in English. Kelab Toastmasters Bahasa Melayu Johor Darul Ta’zim conducts meetings in Bahasa Melayu. Mandarin-speaking visitors can use our Chinese-language enquiry button to ask about English club visits; this directory does not list a Mandarin-language club. Meeting languages were confirmed by the website owner on 9 October 2026.'},
 {question:'Where can I find Toastmasters clubs in Johor, Malaysia?',answer:'This directory lists 16 Toastmasters clubs in Johor, Malaysia, belonging to District 102 Division G across Areas 01–04. Search by club name or number, or filter by area. The roster includes clubs named for Johor Bahru, Iskandar Puteri, Johor Jaya, Pasir Gudang, and Kluang. Meeting information is available for 16 clubs from the supplied workbook, including listings in Batu Pahat, Kluang, Iskandar Puteri, Johor Bahru, and Pasir Gudang. Confirm current arrangements before attending.'},
 {question:'How do I visit a Toastmasters club in Johor?',answer:'Choose a club from the directory, note its club number, and contact the club through its confirmed public contact link or the official Toastmasters club finder. Confirm the venue, meeting time, guest arrangements, and any visitor fees before attending.'},
 {question:'Can beginners visit a Toastmasters meeting?',answer:'You can enquire about visiting as a beginner. Ask the club host what guests can expect and whether participation is optional. Guest policies and access arrangements can differ, particularly for clubs associated with an employer or institution.'},
 {question:'How much does Toastmasters membership cost in Johor?',answer:'Ask your chosen club for its current membership fees, any joining fee, and local club charges. This directory does not publish a single price because charges and payment arrangements must be confirmed with each club.'},
 {question:'Are these public speaking classes in Johor?',answer:'This is a directory of Toastmasters clubs, where members practise communication and leadership through club meetings. It is not a listing of private tuition courses. Ask each club about its learning experience, meeting frequency, and membership arrangements.'},
 {question:'Are meeting times, languages, and venues confirmed?',answer:'Club names, numbers, and areas come from the roster supplied on 8 October 2026. Meeting schedules, formats, venues, and membership access for 16 clubs were imported from the supplied workbook on 8 October 2026. Meeting languages were confirmed by the website owner on 9 October 2026: English for 15 clubs and Bahasa Melayu for Kelab Toastmasters Bahasa Melayu Johor Darul Ta’zim. Direct club contact links remain pending. Conflicting source details are flagged on club pages; confirm current arrangements before attending.'},
];
